### ISSUE TITLE
TypeError: Cannot read property 'main' of undefined

### ISSUE THREAD

**Issue by JustinKuskowski** [derekpovah/aws-lambda-st-iot-button#1]
```
2019-02-02T18:03:24.531Z	33d70781-2ae3-47f3-98e4-51156fac1f31	TypeError: Cannot read property 'main' of undefined
at Request._callback (/var/task/index.js:33:36)
at Request.self.callback (/var/task/node_modules/request/request.js:185:22)
at emitTwo (events.js:126:13)
at Request.emit (events.js:214:7)
at Request.<anonymous> (/var/task/node_modules/request/request.js:1157:10)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1079:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
```

**Comment by derekpovah** [comment]
Thanks for taking the time to open an issue.

Can you provide some context for this error?

**Comment by JustinKuskowski** [comment]
After following your installation instructions, I clicked the IoT button and got this error in cloudwatch.

**Comment by derekpovah** [comment]
I was able to reproduce this issue by removing the device environment variables. Do you have your environment variables set up correctly?
